# import pymysql
#
# # 创建连接
# conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', passwd='password', db='bishe', charset='utf8')
# # 创建游标
# cursor = conn.cursor()
#
# # 执行SQL，并返回收影响行数
# cursor.execute("select * from Student")
# ans = cursor.fetchall()
# print(ans)
#
# # 提交，不然无法保存新建或者修改的数据
# conn.commit()
#
# # 关闭游标
# cursor.close()
# # 关闭连接
# conn.close()


# import numpy as np
#
# a = np.arange(12).reshape(3, 4)
# print(a)
# ans = a[:,1].tolist()
# print(ans)
# print(type(ans))
#
# b = [1, 2, 3]
# c = np.array(b)
# print(c)
# print(type(c))


# import h5py
# import numpy as np
#
# file_path = './tools/0.model/WOW_1bpp.h5'
# f = h5py.File(file_path, 'r')
# for key in f.keys():
#     print(f[key])
# import imageio
# import numpy as np
# from tools.SRNet import SRNet
# import tensorflow as tf
#
#
# model = SRNet(is_training=False, data_format='NCHW')
# print('SRNet model successfully')
# file_path = '/home/dengruizhi/0.paper/4.deng/1.GUI/2.test_photos/cover/1.pgm'
# load_path = '/home/dengruizhi/0.paper/4.deng/pre_model/HUGO_1_Model'
# img = imageio.imread(file_path)
# batch = np.empty(shape=[1, img.shape[0], img.shape[1], 1])
# batch[0, :, :, 0] = img
# output_label = model.build_model(batch)
#
# saver = tf.train.Saver(max_to_keep=10000)
#
# with tf.Session() as sess:
#     model_file = tf.train.latest_checkpoint(load_path)
#     saver.restore(sess, model_file)
#
#     output_label = sess.run(tf.argmax(output_label, 1))
#     print(output_label)

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yanshi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_2(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(788, 634)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(-10, 90, 801, 271))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(300, 190, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(340, 70, 141, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(340, 120, 141, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(220, 60, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(220, 110, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(210, 30, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(-10, 340, 801, 301))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 190, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_3.setGeometry(QtCore.QRect(340, 70, 141, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setGeometry(QtCore.QRect(340, 120, 141, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(220, 60, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(220, 110, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "图像隐写"))
        self.pushButton.setText(_translate("Dialog", "选择待嵌入图像"))
        self.label_4.setText(_translate("Dialog", "隐写术："))
        self.label_5.setText(_translate("Dialog", "嵌入率："))
        self.label.setText(_translate("Dialog", "欢迎进行隐写以及隐写分析操作"))
        self.label_3.setText(_translate("Dialog", "图像隐写分析"))
        self.pushButton_2.setText(_translate("Dialog", "选择隐写分析图像"))
        self.label_6.setText(_translate("Dialog", "隐写术："))
        self.label_7.setText(_translate("Dialog", "嵌入率："))


